name: Rust

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main", "dev"]

concurrency:
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}', github.sha) || format('ci-{0}', github.ref) }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for Linux x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build

      - name: Run tests with native-tls
        run: cargo test --verbose

      - name: Run tests with rustls
        run: cargo test --verbose --no-default-features --features server,client,rustls,noise,websocket-rustls,hot-reload

      - uses: actions/upload-artifact@v4
        with:
          name: rathole-x86_64-unknown-linux-gnu
          path: target/debug/rathole
